// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2ZDGdC-huXz6EkJu-7xkGEd5hWNqhZ0',
    appId: '1:310843735783:web:079069ce1bceca9c28ec42',
    messagingSenderId: '310843735783',
    projectId: 'trab3-angelica',
    authDomain: 'trab3-angelica.firebaseapp.com',
    storageBucket: 'trab3-angelica.appspot.com',
    measurementId: 'G-KJLV3DTBPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZSat_Z13pI6W-V5ib0BXFqMHYu9dLrKg',
    appId: '1:310843735783:android:e7fb316d4be259be28ec42',
    messagingSenderId: '310843735783',
    projectId: 'trab3-angelica',
    storageBucket: 'trab3-angelica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAqkgLL9zNSBi5L_j18nVP9RQdZX9ZPs',
    appId: '1:310843735783:ios:fae4c235954ec3a428ec42',
    messagingSenderId: '310843735783',
    projectId: 'trab3-angelica',
    storageBucket: 'trab3-angelica.appspot.com',
    iosBundleId: 'com.example.flutterSocialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAqkgLL9zNSBi5L_j18nVP9RQdZX9ZPs',
    appId: '1:310843735783:ios:c77c4bcb710f764a28ec42',
    messagingSenderId: '310843735783',
    projectId: 'trab3-angelica',
    storageBucket: 'trab3-angelica.appspot.com',
    iosBundleId: 'com.example.flutterSocialNetwork.RunnerTests',
  );
}
